# @format

title: "FitBook"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2324S2-CS2103T-T17-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
