title: "My Bookshelf"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "https://github.com/AY2324S2-CS2103T-F11-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
