title: "ClassMonitor"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2324S2-CS2103T-F13-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
