title: "FinCliQ"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2324S2-CS2103-F08-1"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
