name: Telegram Pull Request Notifier

on:
  pull_request_target:
    types: [opened, review_requested]

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      # Send a telegram message on pr open or review request
      - name: Pull Request Telegram
        uses: angsongyee/pr-telegram-action
        with:
          bot_token: '${{ secrets.BOTTOKEN }}'
          chat_id: '${{ secrets.CHATID }}'
